package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Banner generated by hbm2java
 */
public class Banner implements java.io.Serializable {

	private int id;
	private User user;
	private Constant constant;
	private Picture picture;
	private String name;
	private String urlAddress;
	private Short conversionRate;
	private Set bannerStatistics = new HashSet(0);

	public Banner() {
	}

	public Banner(int id) {
		this.id = id;
	}

	public Banner(int id, User user, Constant constant, Picture picture,
			String name, String urlAddress, Short conversionRate,
			Set bannerStatistics) {
		this.id = id;
		this.user = user;
		this.constant = constant;
		this.picture = picture;
		this.name = name;
		this.urlAddress = urlAddress;
		this.conversionRate = conversionRate;
		this.bannerStatistics = bannerStatistics;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Constant getConstant() {
		return this.constant;
	}

	public void setConstant(Constant constant) {
		this.constant = constant;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrlAddress() {
		return this.urlAddress;
	}

	public void setUrlAddress(String urlAddress) {
		this.urlAddress = urlAddress;
	}

	public Short getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(Short conversionRate) {
		this.conversionRate = conversionRate;
	}

	public Set getBannerStatistics() {
		return this.bannerStatistics;
	}

	public void setBannerStatistics(Set bannerStatistics) {
		this.bannerStatistics = bannerStatistics;
	}

}
