package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * BannerStatistic generated by hbm2java
 */
public class BannerStatistic implements java.io.Serializable {

	private int id;
	private User user;
	private ClientBrowserStatistic clientBrowserStatistic;
	private Banner banner;
	private Integer locationId;
	private String sessionId;
	private String onPage;
	private Date onDate;

	public BannerStatistic() {
	}

	public BannerStatistic(int id) {
		this.id = id;
	}

	public BannerStatistic(int id, User user,
			ClientBrowserStatistic clientBrowserStatistic, Banner banner,
			Integer locationId, String sessionId, String onPage, Date onDate) {
		this.id = id;
		this.user = user;
		this.clientBrowserStatistic = clientBrowserStatistic;
		this.banner = banner;
		this.locationId = locationId;
		this.sessionId = sessionId;
		this.onPage = onPage;
		this.onDate = onDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public ClientBrowserStatistic getClientBrowserStatistic() {
		return this.clientBrowserStatistic;
	}

	public void setClientBrowserStatistic(
			ClientBrowserStatistic clientBrowserStatistic) {
		this.clientBrowserStatistic = clientBrowserStatistic;
	}

	public Banner getBanner() {
		return this.banner;
	}

	public void setBanner(Banner banner) {
		this.banner = banner;
	}

	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getOnPage() {
		return this.onPage;
	}

	public void setOnPage(String onPage) {
		this.onPage = onPage;
	}

	public Date getOnDate() {
		return this.onDate;
	}

	public void setOnDate(Date onDate) {
		this.onDate = onDate;
	}

}
