package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * CategoryDescription generated by hbm2java
 */
public class CategoryDescription implements java.io.Serializable {

	private int id;
	private Language language;
	private Category category;
	private String name;
	private String description;

	public CategoryDescription() {
	}

	public CategoryDescription(int id) {
		this.id = id;
	}

	public CategoryDescription(int id, Language language, Category category,
			String name, String description) {
		this.id = id;
		this.language = language;
		this.category = category;
		this.name = name;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
