package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private int id;
	private Integer typeId;
	private Set subcategories = new HashSet(0);
	private Set categoryDescriptions = new HashSet(0);

	public Category() {
	}

	public Category(int id) {
		this.id = id;
	}

	public Category(int id, Integer typeId, Set subcategories,
			Set categoryDescriptions) {
		this.id = id;
		this.typeId = typeId;
		this.subcategories = subcategories;
		this.categoryDescriptions = categoryDescriptions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public Set getSubcategories() {
		return this.subcategories;
	}

	public void setSubcategories(Set subcategories) {
		this.subcategories = subcategories;
	}

	public Set getCategoryDescriptions() {
		return this.categoryDescriptions;
	}

	public void setCategoryDescriptions(Set categoryDescriptions) {
		this.categoryDescriptions = categoryDescriptions;
	}

}
