package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CellCarrier generated by hbm2java
 */
public class CellCarrier implements java.io.Serializable {

	private int id;
	private String mnc;
	private String name;
	private Set cellNetworks = new HashSet(0);
	private Set cellTowers = new HashSet(0);

	public CellCarrier() {
	}

	public CellCarrier(int id) {
		this.id = id;
	}

	public CellCarrier(int id, String mnc, String name, Set cellNetworks,
			Set cellTowers) {
		this.id = id;
		this.mnc = mnc;
		this.name = name;
		this.cellNetworks = cellNetworks;
		this.cellTowers = cellTowers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMnc() {
		return this.mnc;
	}

	public void setMnc(String mnc) {
		this.mnc = mnc;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCellNetworks() {
		return this.cellNetworks;
	}

	public void setCellNetworks(Set cellNetworks) {
		this.cellNetworks = cellNetworks;
	}

	public Set getCellTowers() {
		return this.cellTowers;
	}

	public void setCellTowers(Set cellTowers) {
		this.cellTowers = cellTowers;
	}

}
