package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * CellNetwork generated by hbm2java
 */
public class CellNetwork implements java.io.Serializable {

	private int id;
	private Constant constant;
	private CellCarrier cellCarrier;
	private String cellid;
	private String lac;

	public CellNetwork() {
	}

	public CellNetwork(int id) {
		this.id = id;
	}

	public CellNetwork(int id, Constant constant, CellCarrier cellCarrier,
			String cellid, String lac) {
		this.id = id;
		this.constant = constant;
		this.cellCarrier = cellCarrier;
		this.cellid = cellid;
		this.lac = lac;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Constant getConstant() {
		return this.constant;
	}

	public void setConstant(Constant constant) {
		this.constant = constant;
	}

	public CellCarrier getCellCarrier() {
		return this.cellCarrier;
	}

	public void setCellCarrier(CellCarrier cellCarrier) {
		this.cellCarrier = cellCarrier;
	}

	public String getCellid() {
		return this.cellid;
	}

	public void setCellid(String cellid) {
		this.cellid = cellid;
	}

	public String getLac() {
		return this.lac;
	}

	public void setLac(String lac) {
		this.lac = lac;
	}

}
