package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * CellTower generated by hbm2java
 */
public class CellTower implements java.io.Serializable {

	private int id;
	private Location location;
	private CellCarrier cellCarrier;
	private Short range;

	public CellTower() {
	}

	public CellTower(int id) {
		this.id = id;
	}

	public CellTower(int id, Location location, CellCarrier cellCarrier,
			Short range) {
		this.id = id;
		this.location = location;
		this.cellCarrier = cellCarrier;
		this.range = range;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public CellCarrier getCellCarrier() {
		return this.cellCarrier;
	}

	public void setCellCarrier(CellCarrier cellCarrier) {
		this.cellCarrier = cellCarrier;
	}

	public Short getRange() {
		return this.range;
	}

	public void setRange(Short range) {
		this.range = range;
	}

}
