package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ClientBrowserStatistic generated by hbm2java
 */
public class ClientBrowserStatistic implements java.io.Serializable {

	private int id;
	private String ipAddress;
	private String dnsReverseName;
	private String browserName;
	private String browserVersion;
	private String browserPlatform;
	private String httpReferer;
	private Set bannerStatistics = new HashSet(0);
	private Set searchStatistics = new HashSet(0);
	private Set clickstreamStatistics = new HashSet(0);
	private Set hotspotStatistics = new HashSet(0);

	public ClientBrowserStatistic() {
	}

	public ClientBrowserStatistic(int id) {
		this.id = id;
	}

	public ClientBrowserStatistic(int id, String ipAddress,
			String dnsReverseName, String browserName, String browserVersion,
			String browserPlatform, String httpReferer, Set bannerStatistics,
			Set searchStatistics, Set clickstreamStatistics,
			Set hotspotStatistics) {
		this.id = id;
		this.ipAddress = ipAddress;
		this.dnsReverseName = dnsReverseName;
		this.browserName = browserName;
		this.browserVersion = browserVersion;
		this.browserPlatform = browserPlatform;
		this.httpReferer = httpReferer;
		this.bannerStatistics = bannerStatistics;
		this.searchStatistics = searchStatistics;
		this.clickstreamStatistics = clickstreamStatistics;
		this.hotspotStatistics = hotspotStatistics;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getDnsReverseName() {
		return this.dnsReverseName;
	}

	public void setDnsReverseName(String dnsReverseName) {
		this.dnsReverseName = dnsReverseName;
	}

	public String getBrowserName() {
		return this.browserName;
	}

	public void setBrowserName(String browserName) {
		this.browserName = browserName;
	}

	public String getBrowserVersion() {
		return this.browserVersion;
	}

	public void setBrowserVersion(String browserVersion) {
		this.browserVersion = browserVersion;
	}

	public String getBrowserPlatform() {
		return this.browserPlatform;
	}

	public void setBrowserPlatform(String browserPlatform) {
		this.browserPlatform = browserPlatform;
	}

	public String getHttpReferer() {
		return this.httpReferer;
	}

	public void setHttpReferer(String httpReferer) {
		this.httpReferer = httpReferer;
	}

	public Set getBannerStatistics() {
		return this.bannerStatistics;
	}

	public void setBannerStatistics(Set bannerStatistics) {
		this.bannerStatistics = bannerStatistics;
	}

	public Set getSearchStatistics() {
		return this.searchStatistics;
	}

	public void setSearchStatistics(Set searchStatistics) {
		this.searchStatistics = searchStatistics;
	}

	public Set getClickstreamStatistics() {
		return this.clickstreamStatistics;
	}

	public void setClickstreamStatistics(Set clickstreamStatistics) {
		this.clickstreamStatistics = clickstreamStatistics;
	}

	public Set getHotspotStatistics() {
		return this.hotspotStatistics;
	}

	public void setHotspotStatistics(Set hotspotStatistics) {
		this.hotspotStatistics = hotspotStatistics;
	}

}
