package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Constant generated by hbm2java
 */
public class Constant implements java.io.Serializable {

	private int id;
	private String keyName;
	private String keyValue;
	private String code;
	private Set constantNames = new HashSet(0);
	private Set userSessionHistorics = new HashSet(0);
	private Set itemCommentHistorics = new HashSet(0);
	private Set itemHistorics = new HashSet(0);
	private Set banners = new HashSet(0);
	private Set userConfigurationLocations = new HashSet(0);
	private Set events = new HashSet(0);
	private Set persons = new HashSet(0);
	private Set userFriends = new HashSet(0);
	private Set requestsForStatusId = new HashSet(0);
	private Set requestsForTypeId = new HashSet(0);
	private Set cellNetworks = new HashSet(0);
	private Set itemAttributes = new HashSet(0);
	private Set picturesForTypeId = new HashSet(0);
	private Set picturesForExtensionId = new HashSet(0);

	public Constant() {
	}

	public Constant(int id) {
		this.id = id;
	}

	public Constant(int id, String keyName, String keyValue, String code,
			Set constantNames, Set userSessionHistorics,
			Set itemCommentHistorics, Set itemHistorics, Set banners,
			Set userConfigurationLocations, Set events, Set persons,
			Set userFriends, Set requestsForStatusId, Set requestsForTypeId,
			Set cellNetworks, Set itemAttributes, Set picturesForTypeId,
			Set picturesForExtensionId) {
		this.id = id;
		this.keyName = keyName;
		this.keyValue = keyValue;
		this.code = code;
		this.constantNames = constantNames;
		this.userSessionHistorics = userSessionHistorics;
		this.itemCommentHistorics = itemCommentHistorics;
		this.itemHistorics = itemHistorics;
		this.banners = banners;
		this.userConfigurationLocations = userConfigurationLocations;
		this.events = events;
		this.persons = persons;
		this.userFriends = userFriends;
		this.requestsForStatusId = requestsForStatusId;
		this.requestsForTypeId = requestsForTypeId;
		this.cellNetworks = cellNetworks;
		this.itemAttributes = itemAttributes;
		this.picturesForTypeId = picturesForTypeId;
		this.picturesForExtensionId = picturesForExtensionId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getKeyName() {
		return this.keyName;
	}

	public void setKeyName(String keyName) {
		this.keyName = keyName;
	}

	public String getKeyValue() {
		return this.keyValue;
	}

	public void setKeyValue(String keyValue) {
		this.keyValue = keyValue;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set getConstantNames() {
		return this.constantNames;
	}

	public void setConstantNames(Set constantNames) {
		this.constantNames = constantNames;
	}

	public Set getUserSessionHistorics() {
		return this.userSessionHistorics;
	}

	public void setUserSessionHistorics(Set userSessionHistorics) {
		this.userSessionHistorics = userSessionHistorics;
	}

	public Set getItemCommentHistorics() {
		return this.itemCommentHistorics;
	}

	public void setItemCommentHistorics(Set itemCommentHistorics) {
		this.itemCommentHistorics = itemCommentHistorics;
	}

	public Set getItemHistorics() {
		return this.itemHistorics;
	}

	public void setItemHistorics(Set itemHistorics) {
		this.itemHistorics = itemHistorics;
	}

	public Set getBanners() {
		return this.banners;
	}

	public void setBanners(Set banners) {
		this.banners = banners;
	}

	public Set getUserConfigurationLocations() {
		return this.userConfigurationLocations;
	}

	public void setUserConfigurationLocations(Set userConfigurationLocations) {
		this.userConfigurationLocations = userConfigurationLocations;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

	public Set getUserFriends() {
		return this.userFriends;
	}

	public void setUserFriends(Set userFriends) {
		this.userFriends = userFriends;
	}

	public Set getRequestsForStatusId() {
		return this.requestsForStatusId;
	}

	public void setRequestsForStatusId(Set requestsForStatusId) {
		this.requestsForStatusId = requestsForStatusId;
	}

	public Set getRequestsForTypeId() {
		return this.requestsForTypeId;
	}

	public void setRequestsForTypeId(Set requestsForTypeId) {
		this.requestsForTypeId = requestsForTypeId;
	}

	public Set getCellNetworks() {
		return this.cellNetworks;
	}

	public void setCellNetworks(Set cellNetworks) {
		this.cellNetworks = cellNetworks;
	}

	public Set getItemAttributes() {
		return this.itemAttributes;
	}

	public void setItemAttributes(Set itemAttributes) {
		this.itemAttributes = itemAttributes;
	}

	public Set getPicturesForTypeId() {
		return this.picturesForTypeId;
	}

	public void setPicturesForTypeId(Set picturesForTypeId) {
		this.picturesForTypeId = picturesForTypeId;
	}

	public Set getPicturesForExtensionId() {
		return this.picturesForExtensionId;
	}

	public void setPicturesForExtensionId(Set picturesForExtensionId) {
		this.picturesForExtensionId = picturesForExtensionId;
	}

}
