package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * ConstantName generated by hbm2java
 */
public class ConstantName implements java.io.Serializable {

	private int id;
	private Constant constant;
	private Language language;
	private String name;

	public ConstantName() {
	}

	public ConstantName(int id) {
		this.id = id;
	}

	public ConstantName(int id, Constant constant, Language language,
			String name) {
		this.id = id;
		this.constant = constant;
		this.language = language;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Constant getConstant() {
		return this.constant;
	}

	public void setConstant(Constant constant) {
		this.constant = constant;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
