package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private int id;
	private Picture picture;
	private Person person;
	private String workPhoneNumber;
	private String mobilePhoneNumber;
	private String homePhoneNumber;
	private String skypeContact;
	private String emailAddress;
	private String imAddress;
	private String homepageAddress;
	private Set itemContacts = new HashSet(0);

	public Contact() {
	}

	public Contact(int id) {
		this.id = id;
	}

	public Contact(int id, Picture picture, Person person,
			String workPhoneNumber, String mobilePhoneNumber,
			String homePhoneNumber, String skypeContact, String emailAddress,
			String imAddress, String homepageAddress, Set itemContacts) {
		this.id = id;
		this.picture = picture;
		this.person = person;
		this.workPhoneNumber = workPhoneNumber;
		this.mobilePhoneNumber = mobilePhoneNumber;
		this.homePhoneNumber = homePhoneNumber;
		this.skypeContact = skypeContact;
		this.emailAddress = emailAddress;
		this.imAddress = imAddress;
		this.homepageAddress = homepageAddress;
		this.itemContacts = itemContacts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public String getWorkPhoneNumber() {
		return this.workPhoneNumber;
	}

	public void setWorkPhoneNumber(String workPhoneNumber) {
		this.workPhoneNumber = workPhoneNumber;
	}

	public String getMobilePhoneNumber() {
		return this.mobilePhoneNumber;
	}

	public void setMobilePhoneNumber(String mobilePhoneNumber) {
		this.mobilePhoneNumber = mobilePhoneNumber;
	}

	public String getHomePhoneNumber() {
		return this.homePhoneNumber;
	}

	public void setHomePhoneNumber(String homePhoneNumber) {
		this.homePhoneNumber = homePhoneNumber;
	}

	public String getSkypeContact() {
		return this.skypeContact;
	}

	public void setSkypeContact(String skypeContact) {
		this.skypeContact = skypeContact;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getImAddress() {
		return this.imAddress;
	}

	public void setImAddress(String imAddress) {
		this.imAddress = imAddress;
	}

	public String getHomepageAddress() {
		return this.homepageAddress;
	}

	public void setHomepageAddress(String homepageAddress) {
		this.homepageAddress = homepageAddress;
	}

	public Set getItemContacts() {
		return this.itemContacts;
	}

	public void setItemContacts(Set itemContacts) {
		this.itemContacts = itemContacts;
	}

}
