package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * CountryName generated by hbm2java
 */
public class CountryName implements java.io.Serializable {

	private int id;
	private Country country;
	private Language language;
	private String name;

	public CountryName() {
	}

	public CountryName(int id) {
		this.id = id;
	}

	public CountryName(int id, Country country, Language language, String name) {
		this.id = id;
		this.country = country;
		this.language = language;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
