package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

	private int id;
	private String code;
	private Character symbol;
	private Double conversionRate;
	private Set itemPrices = new HashSet(0);
	private Set countries = new HashSet(0);
	private Set currencyNames = new HashSet(0);

	public Currency() {
	}

	public Currency(int id) {
		this.id = id;
	}

	public Currency(int id, String code, Character symbol,
			Double conversionRate, Set itemPrices, Set countries,
			Set currencyNames) {
		this.id = id;
		this.code = code;
		this.symbol = symbol;
		this.conversionRate = conversionRate;
		this.itemPrices = itemPrices;
		this.countries = countries;
		this.currencyNames = currencyNames;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Character getSymbol() {
		return this.symbol;
	}

	public void setSymbol(Character symbol) {
		this.symbol = symbol;
	}

	public Double getConversionRate() {
		return this.conversionRate;
	}

	public void setConversionRate(Double conversionRate) {
		this.conversionRate = conversionRate;
	}

	public Set getItemPrices() {
		return this.itemPrices;
	}

	public void setItemPrices(Set itemPrices) {
		this.itemPrices = itemPrices;
	}

	public Set getCountries() {
		return this.countries;
	}

	public void setCountries(Set countries) {
		this.countries = countries;
	}

	public Set getCurrencyNames() {
		return this.currencyNames;
	}

	public void setCurrencyNames(Set currencyNames) {
		this.currencyNames = currencyNames;
	}

}
