package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * CurrencyName generated by hbm2java
 */
public class CurrencyName implements java.io.Serializable {

	private int id;
	private Currency currency;
	private Language language;
	private String name;

	public CurrencyName() {
	}

	public CurrencyName(int id) {
		this.id = id;
	}

	public CurrencyName(int id, Currency currency, Language language,
			String name) {
		this.id = id;
		this.currency = currency;
		this.language = language;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
