package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * EventDescription generated by hbm2java
 */
public class EventDescription implements java.io.Serializable {

	private int id;
	private Event event;
	private Language language;
	private String name;
	private String description;

	public EventDescription() {
	}

	public EventDescription(int id) {
		this.id = id;
	}

	public EventDescription(int id, Event event, Language language,
			String name, String description) {
		this.id = id;
		this.event = event;
		this.language = language;
		this.name = name;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
