package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * HotspotStatistic generated by hbm2java
 */
public class HotspotStatistic implements java.io.Serializable {

	private int id;
	private User user;
	private ClientBrowserStatistic clientBrowserStatistic;
	private Location location;
	private String sessionId;
	private String onPath;
	private String onPage;
	private Date onDate;
	private Short XPosition;
	private Short YPosition;
	private Short browserHeight;
	private Short browserWidth;

	public HotspotStatistic() {
	}

	public HotspotStatistic(int id) {
		this.id = id;
	}

	public HotspotStatistic(int id, User user,
			ClientBrowserStatistic clientBrowserStatistic, Location location,
			String sessionId, String onPath, String onPage, Date onDate,
			Short XPosition, Short YPosition, Short browserHeight,
			Short browserWidth) {
		this.id = id;
		this.user = user;
		this.clientBrowserStatistic = clientBrowserStatistic;
		this.location = location;
		this.sessionId = sessionId;
		this.onPath = onPath;
		this.onPage = onPage;
		this.onDate = onDate;
		this.XPosition = XPosition;
		this.YPosition = YPosition;
		this.browserHeight = browserHeight;
		this.browserWidth = browserWidth;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public ClientBrowserStatistic getClientBrowserStatistic() {
		return this.clientBrowserStatistic;
	}

	public void setClientBrowserStatistic(
			ClientBrowserStatistic clientBrowserStatistic) {
		this.clientBrowserStatistic = clientBrowserStatistic;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getOnPath() {
		return this.onPath;
	}

	public void setOnPath(String onPath) {
		this.onPath = onPath;
	}

	public String getOnPage() {
		return this.onPage;
	}

	public void setOnPage(String onPage) {
		this.onPage = onPage;
	}

	public Date getOnDate() {
		return this.onDate;
	}

	public void setOnDate(Date onDate) {
		this.onDate = onDate;
	}

	public Short getXPosition() {
		return this.XPosition;
	}

	public void setXPosition(Short XPosition) {
		this.XPosition = XPosition;
	}

	public Short getYPosition() {
		return this.YPosition;
	}

	public void setYPosition(Short YPosition) {
		this.YPosition = YPosition;
	}

	public Short getBrowserHeight() {
		return this.browserHeight;
	}

	public void setBrowserHeight(Short browserHeight) {
		this.browserHeight = browserHeight;
	}

	public Short getBrowserWidth() {
		return this.browserWidth;
	}

	public void setBrowserWidth(Short browserWidth) {
		this.browserWidth = browserWidth;
	}

}
