package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * ItemResume generated by hbm2java
 */
public class ItemResume implements java.io.Serializable {

	private int id;
	private Item item;
	private Language language;
	private String resume;

	public ItemResume() {
	}

	public ItemResume(int id) {
		this.id = id;
	}

	public ItemResume(int id, Item item, Language language, String resume) {
		this.id = id;
		this.item = item;
		this.language = language;
		this.resume = resume;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

}
