package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * ItemAttribute generated by hbm2java
 */
public class ItemAttribute implements java.io.Serializable {

	private int id;
	private Item item;
	private Constant constant;
	private String value;

	public ItemAttribute() {
	}

	public ItemAttribute(int id) {
		this.id = id;
	}

	public ItemAttribute(int id, Item item, Constant constant, String value) {
		this.id = id;
		this.item = item;
		this.constant = constant;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Constant getConstant() {
		return this.constant;
	}

	public void setConstant(Constant constant) {
		this.constant = constant;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
