package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ItemContact generated by hbm2java
 */
public class ItemContact implements java.io.Serializable {

	private int id;
	private Contact contact;
	private Set items = new HashSet(0);

	public ItemContact() {
	}

	public ItemContact(int id) {
		this.id = id;
	}

	public ItemContact(int id, Contact contact, Set items) {
		this.id = id;
		this.contact = contact;
		this.items = items;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
