package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemComment generated by hbm2java
 */
public class ItemComment implements java.io.Serializable {

	private int id;
	private User user;
	private Item item;
	private Short calification;
	private Date onDate;
	private Short ratedFavorably;
	private Short ratedNotFavorably;
	private Set itemCommentHistorics = new HashSet(0);
	private Set itemCommentPictures = new HashSet(0);
	private Set itemCommentTexts = new HashSet(0);

	public ItemComment() {
	}

	public ItemComment(int id) {
		this.id = id;
	}

	public ItemComment(int id, User user, Item item, Short calification,
			Date onDate, Short ratedFavorably, Short ratedNotFavorably,
			Set itemCommentHistorics, Set itemCommentPictures,
			Set itemCommentTexts) {
		this.id = id;
		this.user = user;
		this.item = item;
		this.calification = calification;
		this.onDate = onDate;
		this.ratedFavorably = ratedFavorably;
		this.ratedNotFavorably = ratedNotFavorably;
		this.itemCommentHistorics = itemCommentHistorics;
		this.itemCommentPictures = itemCommentPictures;
		this.itemCommentTexts = itemCommentTexts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Short getCalification() {
		return this.calification;
	}

	public void setCalification(Short calification) {
		this.calification = calification;
	}

	public Date getOnDate() {
		return this.onDate;
	}

	public void setOnDate(Date onDate) {
		this.onDate = onDate;
	}

	public Short getRatedFavorably() {
		return this.ratedFavorably;
	}

	public void setRatedFavorably(Short ratedFavorably) {
		this.ratedFavorably = ratedFavorably;
	}

	public Short getRatedNotFavorably() {
		return this.ratedNotFavorably;
	}

	public void setRatedNotFavorably(Short ratedNotFavorably) {
		this.ratedNotFavorably = ratedNotFavorably;
	}

	public Set getItemCommentHistorics() {
		return this.itemCommentHistorics;
	}

	public void setItemCommentHistorics(Set itemCommentHistorics) {
		this.itemCommentHistorics = itemCommentHistorics;
	}

	public Set getItemCommentPictures() {
		return this.itemCommentPictures;
	}

	public void setItemCommentPictures(Set itemCommentPictures) {
		this.itemCommentPictures = itemCommentPictures;
	}

	public Set getItemCommentTexts() {
		return this.itemCommentTexts;
	}

	public void setItemCommentTexts(Set itemCommentTexts) {
		this.itemCommentTexts = itemCommentTexts;
	}

}
