package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemPrice generated by hbm2java
 */
public class ItemPrice implements java.io.Serializable {

	private int id;
	private Currency currency;
	private BigDecimal value;
	private Set itemsForMinPriceId = new HashSet(0);
	private Set itemsForMaxPriceId = new HashSet(0);

	public ItemPrice() {
	}

	public ItemPrice(int id) {
		this.id = id;
	}

	public ItemPrice(int id, Currency currency, BigDecimal value,
			Set itemsForMinPriceId, Set itemsForMaxPriceId) {
		this.id = id;
		this.currency = currency;
		this.value = value;
		this.itemsForMinPriceId = itemsForMinPriceId;
		this.itemsForMaxPriceId = itemsForMaxPriceId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	public Set getItemsForMinPriceId() {
		return this.itemsForMinPriceId;
	}

	public void setItemsForMinPriceId(Set itemsForMinPriceId) {
		this.itemsForMinPriceId = itemsForMinPriceId;
	}

	public Set getItemsForMaxPriceId() {
		return this.itemsForMaxPriceId;
	}

	public void setItemsForMaxPriceId(Set itemsForMaxPriceId) {
		this.itemsForMaxPriceId = itemsForMaxPriceId;
	}

}
