package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ItemLocation generated by hbm2java
 */
public class ItemLocation implements java.io.Serializable {

	private int id;
	private Street street;
	private Location location;
	private String streetOutsideNumber;
	private String streetInsideNumber;
	private String locationName;
	private Set items = new HashSet(0);

	public ItemLocation() {
	}

	public ItemLocation(int id) {
		this.id = id;
	}

	public ItemLocation(int id, Street street, Location location,
			String streetOutsideNumber, String streetInsideNumber,
			String locationName, Set items) {
		this.id = id;
		this.street = street;
		this.location = location;
		this.streetOutsideNumber = streetOutsideNumber;
		this.streetInsideNumber = streetInsideNumber;
		this.locationName = locationName;
		this.items = items;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Street getStreet() {
		return this.street;
	}

	public void setStreet(Street street) {
		this.street = street;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getStreetOutsideNumber() {
		return this.streetOutsideNumber;
	}

	public void setStreetOutsideNumber(String streetOutsideNumber) {
		this.streetOutsideNumber = streetOutsideNumber;
	}

	public String getStreetInsideNumber() {
		return this.streetInsideNumber;
	}

	public void setStreetInsideNumber(String streetInsideNumber) {
		this.streetInsideNumber = streetInsideNumber;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
