package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * ItemCommentText generated by hbm2java
 */
public class ItemCommentText implements java.io.Serializable {

	private int id;
	private ItemComment itemComment;
	private Language language;
	private String comments;

	public ItemCommentText() {
	}

	public ItemCommentText(int id) {
		this.id = id;
	}

	public ItemCommentText(int id, ItemComment itemComment, Language language,
			String comments) {
		this.id = id;
		this.itemComment = itemComment;
		this.language = language;
		this.comments = comments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ItemComment getItemComment() {
		return this.itemComment;
	}

	public void setItemComment(ItemComment itemComment) {
		this.itemComment = itemComment;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
