package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * Label generated by hbm2java
 */
public class Label implements java.io.Serializable {

	private int id;
	private Language language;
	private String name;
	private String value;

	public Label() {
	}

	public Label(int id) {
		this.id = id;
	}

	public Label(int id, Language language, String name, String value) {
		this.id = id;
		this.language = language;
		this.name = name;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
