package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private int id;
	private Constant constant;
	private String name;
	private String firstname;
	private String lastname;
	private Short birthDay;
	private Short birthMonth;
	private Short birthYear;
	private Set contacts = new HashSet(0);
	private Set users = new HashSet(0);

	public Person() {
	}

	public Person(int id) {
		this.id = id;
	}

	public Person(int id, Constant constant, String name, String firstname,
			String lastname, Short birthDay, Short birthMonth, Short birthYear,
			Set contacts, Set users) {
		this.id = id;
		this.constant = constant;
		this.name = name;
		this.firstname = firstname;
		this.lastname = lastname;
		this.birthDay = birthDay;
		this.birthMonth = birthMonth;
		this.birthYear = birthYear;
		this.contacts = contacts;
		this.users = users;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Constant getConstant() {
		return this.constant;
	}

	public void setConstant(Constant constant) {
		this.constant = constant;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Short getBirthDay() {
		return this.birthDay;
	}

	public void setBirthDay(Short birthDay) {
		this.birthDay = birthDay;
	}

	public Short getBirthMonth() {
		return this.birthMonth;
	}

	public void setBirthMonth(Short birthMonth) {
		this.birthMonth = birthMonth;
	}

	public Short getBirthYear() {
		return this.birthYear;
	}

	public void setBirthYear(Short birthYear) {
		this.birthYear = birthYear;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
