package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * PictureComment generated by hbm2java
 */
public class PictureComment implements java.io.Serializable {

	private int id;
	private Language language;
	private Picture picture;
	private String comments;

	public PictureComment() {
	}

	public PictureComment(int id) {
		this.id = id;
	}

	public PictureComment(int id, Language language, Picture picture,
			String comments) {
		this.id = id;
		this.language = language;
		this.picture = picture;
		this.comments = comments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
