package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * PostalCode generated by hbm2java
 */
public class PostalCode implements java.io.Serializable {

	private int id;
	private Zone zone;
	private String code;

	public PostalCode() {
	}

	public PostalCode(int id) {
		this.id = id;
	}

	public PostalCode(int id, Zone zone, String code) {
		this.id = id;
		this.zone = zone;
		this.code = code;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
