package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * RecommenderDiff generated by hbm2java
 */
public class RecommenderDiff implements java.io.Serializable {

	private int id;
	private Item itemByItemIdA;
	private Item itemByItemIdB;
	private Double averageDiff;
	private Short count;

	public RecommenderDiff() {
	}

	public RecommenderDiff(int id) {
		this.id = id;
	}

	public RecommenderDiff(int id, Item itemByItemIdA, Item itemByItemIdB,
			Double averageDiff, Short count) {
		this.id = id;
		this.itemByItemIdA = itemByItemIdA;
		this.itemByItemIdB = itemByItemIdB;
		this.averageDiff = averageDiff;
		this.count = count;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Item getItemByItemIdA() {
		return this.itemByItemIdA;
	}

	public void setItemByItemIdA(Item itemByItemIdA) {
		this.itemByItemIdA = itemByItemIdA;
	}

	public Item getItemByItemIdB() {
		return this.itemByItemIdB;
	}

	public void setItemByItemIdB(Item itemByItemIdB) {
		this.itemByItemIdB = itemByItemIdB;
	}

	public Double getAverageDiff() {
		return this.averageDiff;
	}

	public void setAverageDiff(Double averageDiff) {
		this.averageDiff = averageDiff;
	}

	public Short getCount() {
		return this.count;
	}

	public void setCount(Short count) {
		this.count = count;
	}

}
