package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * RequestComment generated by hbm2java
 */
public class RequestComment implements java.io.Serializable {

	private int id;
	private Language language;
	private Request request;
	private String comments;

	public RequestComment() {
	}

	public RequestComment(int id) {
		this.id = id;
	}

	public RequestComment(int id, Language language, Request request,
			String comments) {
		this.id = id;
		this.language = language;
		this.request = request;
		this.comments = comments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
