package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request implements java.io.Serializable {

	private int id;
	private Constant constantByTypeId;
	private User userByToUserId;
	private User userByFromUserId;
	private Constant constantByStatusId;
	private Date onDate;
	private Boolean isClosed;
	private Date closedOnDate;
	private Set requestComments = new HashSet(0);

	public Request() {
	}

	public Request(int id) {
		this.id = id;
	}

	public Request(int id, Constant constantByTypeId, User userByToUserId,
			User userByFromUserId, Constant constantByStatusId, Date onDate,
			Boolean isClosed, Date closedOnDate, Set requestComments) {
		this.id = id;
		this.constantByTypeId = constantByTypeId;
		this.userByToUserId = userByToUserId;
		this.userByFromUserId = userByFromUserId;
		this.constantByStatusId = constantByStatusId;
		this.onDate = onDate;
		this.isClosed = isClosed;
		this.closedOnDate = closedOnDate;
		this.requestComments = requestComments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Constant getConstantByTypeId() {
		return this.constantByTypeId;
	}

	public void setConstantByTypeId(Constant constantByTypeId) {
		this.constantByTypeId = constantByTypeId;
	}

	public User getUserByToUserId() {
		return this.userByToUserId;
	}

	public void setUserByToUserId(User userByToUserId) {
		this.userByToUserId = userByToUserId;
	}

	public User getUserByFromUserId() {
		return this.userByFromUserId;
	}

	public void setUserByFromUserId(User userByFromUserId) {
		this.userByFromUserId = userByFromUserId;
	}

	public Constant getConstantByStatusId() {
		return this.constantByStatusId;
	}

	public void setConstantByStatusId(Constant constantByStatusId) {
		this.constantByStatusId = constantByStatusId;
	}

	public Date getOnDate() {
		return this.onDate;
	}

	public void setOnDate(Date onDate) {
		this.onDate = onDate;
	}

	public Boolean getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Boolean isClosed) {
		this.isClosed = isClosed;
	}

	public Date getClosedOnDate() {
		return this.closedOnDate;
	}

	public void setClosedOnDate(Date closedOnDate) {
		this.closedOnDate = closedOnDate;
	}

	public Set getRequestComments() {
		return this.requestComments;
	}

	public void setRequestComments(Set requestComments) {
		this.requestComments = requestComments;
	}

}
