package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * SearchStatistic generated by hbm2java
 */
public class SearchStatistic implements java.io.Serializable {

	private int id;
	private User user;
	private ClientBrowserStatistic clientBrowserStatistic;
	private Location location;
	private String sessionId;
	private String keyterm;
	private String onPage;
	private Date onDate;

	public SearchStatistic() {
	}

	public SearchStatistic(int id) {
		this.id = id;
	}

	public SearchStatistic(int id, User user,
			ClientBrowserStatistic clientBrowserStatistic, Location location,
			String sessionId, String keyterm, String onPage, Date onDate) {
		this.id = id;
		this.user = user;
		this.clientBrowserStatistic = clientBrowserStatistic;
		this.location = location;
		this.sessionId = sessionId;
		this.keyterm = keyterm;
		this.onPage = onPage;
		this.onDate = onDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public ClientBrowserStatistic getClientBrowserStatistic() {
		return this.clientBrowserStatistic;
	}

	public void setClientBrowserStatistic(
			ClientBrowserStatistic clientBrowserStatistic) {
		this.clientBrowserStatistic = clientBrowserStatistic;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getKeyterm() {
		return this.keyterm;
	}

	public void setKeyterm(String keyterm) {
		this.keyterm = keyterm;
	}

	public String getOnPage() {
		return this.onPage;
	}

	public void setOnPage(String onPage) {
		this.onPage = onPage;
	}

	public Date getOnDate() {
		return this.onDate;
	}

	public void setOnDate(Date onDate) {
		this.onDate = onDate;
	}

}
