package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Street generated by hbm2java
 */
public class Street implements java.io.Serializable {

	private int id;
	private Zone zone;
	private String name;
	private Set itemLocations = new HashSet(0);

	public Street() {
	}

	public Street(int id) {
		this.id = id;
	}

	public Street(int id, Zone zone, String name, Set itemLocations) {
		this.id = id;
		this.zone = zone;
		this.name = name;
		this.itemLocations = itemLocations;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getItemLocations() {
		return this.itemLocations;
	}

	public void setItemLocations(Set itemLocations) {
		this.itemLocations = itemLocations;
	}

}
