package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * SubcategoryDescription generated by hbm2java
 */
public class SubcategoryDescription implements java.io.Serializable {

	private int id;
	private Language language;
	private Subcategory subcategory;
	private String name;
	private String description;

	public SubcategoryDescription() {
	}

	public SubcategoryDescription(int id) {
		this.id = id;
	}

	public SubcategoryDescription(int id, Language language,
			Subcategory subcategory, String name, String description) {
		this.id = id;
		this.language = language;
		this.subcategory = subcategory;
		this.name = name;
		this.description = description;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Subcategory getSubcategory() {
		return this.subcategory;
	}

	public void setSubcategory(Subcategory subcategory) {
		this.subcategory = subcategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
