package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * UserConfigurationLocation generated by hbm2java
 */
public class UserConfigurationLocation implements java.io.Serializable {

	private int id;
	private Constant constant;
	private Location location;
	private UserConfiguration userConfiguration;
	private String sessionId;
	private String ipAddress;
	private Date onDate;
	private String name;
	private Boolean isCurrentLocation;

	public UserConfigurationLocation() {
	}

	public UserConfigurationLocation(int id) {
		this.id = id;
	}

	public UserConfigurationLocation(int id, Constant constant,
			Location location, UserConfiguration userConfiguration,
			String sessionId, String ipAddress, Date onDate, String name,
			Boolean isCurrentLocation) {
		this.id = id;
		this.constant = constant;
		this.location = location;
		this.userConfiguration = userConfiguration;
		this.sessionId = sessionId;
		this.ipAddress = ipAddress;
		this.onDate = onDate;
		this.name = name;
		this.isCurrentLocation = isCurrentLocation;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Constant getConstant() {
		return this.constant;
	}

	public void setConstant(Constant constant) {
		this.constant = constant;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public UserConfiguration getUserConfiguration() {
		return this.userConfiguration;
	}

	public void setUserConfiguration(UserConfiguration userConfiguration) {
		this.userConfiguration = userConfiguration;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public Date getOnDate() {
		return this.onDate;
	}

	public void setOnDate(Date onDate) {
		this.onDate = onDate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getIsCurrentLocation() {
		return this.isCurrentLocation;
	}

	public void setIsCurrentLocation(Boolean isCurrentLocation) {
		this.isCurrentLocation = isCurrentLocation;
	}

}
