package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private UserProfile userProfile;
	private UserSession userSession;
	private UserConfiguration userConfiguration;
	private UserGroup userGroup;
	private Person person;
	private Set searchStatistics = new HashSet(0);
	private Set banners = new HashSet(0);
	private Set clickstreamStatistics = new HashSet(0);
	private Set itemSubmittedBies = new HashSet(0);
	private Set bannerStatistics = new HashSet(0);
	private Set events = new HashSet(0);
	private Set hotspotStatistics = new HashSet(0);
	private Set userFavorites = new HashSet(0);
	private Set userFriends = new HashSet(0);
	private Set requestsForToUserId = new HashSet(0);
	private Set itemComments = new HashSet(0);
	private Set requestsForFromUserId = new HashSet(0);
	private Set itemHistorics = new HashSet(0);

	public User() {
	}

	public User(int id) {
		this.id = id;
	}

	public User(int id, UserProfile userProfile, UserSession userSession,
			UserConfiguration userConfiguration, UserGroup userGroup,
			Person person, Set searchStatistics, Set banners,
			Set clickstreamStatistics, Set itemSubmittedBies,
			Set bannerStatistics, Set events, Set hotspotStatistics,
			Set userFavorites, Set userFriends, Set requestsForToUserId,
			Set itemComments, Set requestsForFromUserId, Set itemHistorics) {
		this.id = id;
		this.userProfile = userProfile;
		this.userSession = userSession;
		this.userConfiguration = userConfiguration;
		this.userGroup = userGroup;
		this.person = person;
		this.searchStatistics = searchStatistics;
		this.banners = banners;
		this.clickstreamStatistics = clickstreamStatistics;
		this.itemSubmittedBies = itemSubmittedBies;
		this.bannerStatistics = bannerStatistics;
		this.events = events;
		this.hotspotStatistics = hotspotStatistics;
		this.userFavorites = userFavorites;
		this.userFriends = userFriends;
		this.requestsForToUserId = requestsForToUserId;
		this.itemComments = itemComments;
		this.requestsForFromUserId = requestsForFromUserId;
		this.itemHistorics = itemHistorics;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	public UserSession getUserSession() {
		return this.userSession;
	}

	public void setUserSession(UserSession userSession) {
		this.userSession = userSession;
	}

	public UserConfiguration getUserConfiguration() {
		return this.userConfiguration;
	}

	public void setUserConfiguration(UserConfiguration userConfiguration) {
		this.userConfiguration = userConfiguration;
	}

	public UserGroup getUserGroup() {
		return this.userGroup;
	}

	public void setUserGroup(UserGroup userGroup) {
		this.userGroup = userGroup;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Set getSearchStatistics() {
		return this.searchStatistics;
	}

	public void setSearchStatistics(Set searchStatistics) {
		this.searchStatistics = searchStatistics;
	}

	public Set getBanners() {
		return this.banners;
	}

	public void setBanners(Set banners) {
		this.banners = banners;
	}

	public Set getClickstreamStatistics() {
		return this.clickstreamStatistics;
	}

	public void setClickstreamStatistics(Set clickstreamStatistics) {
		this.clickstreamStatistics = clickstreamStatistics;
	}

	public Set getItemSubmittedBies() {
		return this.itemSubmittedBies;
	}

	public void setItemSubmittedBies(Set itemSubmittedBies) {
		this.itemSubmittedBies = itemSubmittedBies;
	}

	public Set getBannerStatistics() {
		return this.bannerStatistics;
	}

	public void setBannerStatistics(Set bannerStatistics) {
		this.bannerStatistics = bannerStatistics;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

	public Set getHotspotStatistics() {
		return this.hotspotStatistics;
	}

	public void setHotspotStatistics(Set hotspotStatistics) {
		this.hotspotStatistics = hotspotStatistics;
	}

	public Set getUserFavorites() {
		return this.userFavorites;
	}

	public void setUserFavorites(Set userFavorites) {
		this.userFavorites = userFavorites;
	}

	public Set getUserFriends() {
		return this.userFriends;
	}

	public void setUserFriends(Set userFriends) {
		this.userFriends = userFriends;
	}

	public Set getRequestsForToUserId() {
		return this.requestsForToUserId;
	}

	public void setRequestsForToUserId(Set requestsForToUserId) {
		this.requestsForToUserId = requestsForToUserId;
	}

	public Set getItemComments() {
		return this.itemComments;
	}

	public void setItemComments(Set itemComments) {
		this.itemComments = itemComments;
	}

	public Set getRequestsForFromUserId() {
		return this.requestsForFromUserId;
	}

	public void setRequestsForFromUserId(Set requestsForFromUserId) {
		this.requestsForFromUserId = requestsForFromUserId;
	}

	public Set getItemHistorics() {
		return this.itemHistorics;
	}

	public void setItemHistorics(Set itemHistorics) {
		this.itemHistorics = itemHistorics;
	}

}
