package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * UserSession generated by hbm2java
 */
public class UserSession implements java.io.Serializable {

	private int id;
	private String login;
	private String password;
	private Set users = new HashSet(0);
	private Set userSessionHistorics = new HashSet(0);

	public UserSession() {
	}

	public UserSession(int id) {
		this.id = id;
	}

	public UserSession(int id, String login, String password, Set users,
			Set userSessionHistorics) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.users = users;
		this.userSessionHistorics = userSessionHistorics;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getUserSessionHistorics() {
		return this.userSessionHistorics;
	}

	public void setUserSessionHistorics(Set userSessionHistorics) {
		this.userSessionHistorics = userSessionHistorics;
	}

}
