package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

/**
 * UserFavoriteComment generated by hbm2java
 */
public class UserFavoriteComment implements java.io.Serializable {

	private int id;
	private UserFavorite userFavorite;
	private Language language;
	private String comments;

	public UserFavoriteComment() {
	}

	public UserFavoriteComment(int id) {
		this.id = id;
	}

	public UserFavoriteComment(int id, UserFavorite userFavorite,
			Language language, String comments) {
		this.id = id;
		this.userFavorite = userFavorite;
		this.language = language;
		this.comments = comments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UserFavorite getUserFavorite() {
		return this.userFavorite;
	}

	public void setUserFavorite(UserFavorite userFavorite) {
		this.userFavorite = userFavorite;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
