package mx.com.recomendare.db.entities;

// Generated May 13, 2009 4:44:37 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserFavorite generated by hbm2java
 */
public class UserFavorite implements java.io.Serializable {

	private int id;
	private User user;
	private Item item;
	private Date createdOn;
	private Set userFavoriteComments = new HashSet(0);

	public UserFavorite() {
	}

	public UserFavorite(int id) {
		this.id = id;
	}

	public UserFavorite(int id, User user, Item item, Date createdOn,
			Set userFavoriteComments) {
		this.id = id;
		this.user = user;
		this.item = item;
		this.createdOn = createdOn;
		this.userFavoriteComments = userFavoriteComments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Set getUserFavoriteComments() {
		return this.userFavoriteComments;
	}

	public void setUserFavoriteComments(Set userFavoriteComments) {
		this.userFavoriteComments = userFavoriteComments;
	}

}
